### ISSUE TITLE
Encountering no function clause error Holidays.Define.on_static/2

### ISSUE THREAD

**Issue by silverp1** [CoderDennis/holidays#13]
Hi there! Interesting project you have going here and concidentally exactly what I need for a project I'm working on. Unfortunately I'm running into some hiccups getting it running, I'm seeing:

```
** (FunctionClauseError) no function clause matching in Holidays.Define.on_static/2
    (holidays 0.2.4) lib/holidays/define.ex:31: Holidays.Define.on_static([{"Christmas Day", 12, 25, [:nyse]}, {"Independence Day", 7, 4, [:nyse]}, {"New Year's Day", 1, 1, [:nyse]}], ~N[2021-02-15 00:00:00])
    (holidays 0.2.4) lib/holidays/define.ex:26: Holidays.Define.on_all/2
    (holidays 0.2.4) lib/holidays/define.ex:94: Holidays.Define.handle_call/3
    (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from :precompute_worker): {:on, ~N[2021-02-15 00:00:00], [:nyse]}
State: %{fun: [{"Good Friday", {Holidays, :easter, [:year], -2}, [:nyse]}], nth: [{"Thanksgiving", 11, :fourth, :thursday, [:nyse]}, {"Labor Day", 9, :first, :monday, [:nyse]}, {"Memorial Day", 5, :last, :monday, [:nyse]}, {"Presidents' Day", 2, :third, :monday, [:nyse]}, {"Martin Luther King, Jr. Day", 1, :third, :monday, [:nyse]}], static: [{"Christmas Day", 12, 25, [:nyse]}, {"Independence Day", 7, 4, [:nyse]}, {"New Year's Day", 1, 1, [:nyse]}]}
Client :precompute_worker is alive
```

I am starting the `nyse` definition in my application file like so:

```
Holidays.Definitions.Nyse.init()
```

And I'm getting `:ok` back from that. 

I'm specifically calling `on/1` like so: 

```
  def is_bank_holiday?(date) do
    Holidays.on(date, [:nyse])
    |> IO.inspect
  end
```

Am I doing something wrong here? Appreciate any help you can provide, thanks!

**Comment by silverp1** [comment]
Ah I see, this can only accept erl formatted dates, switched that up and it appears happy. Might be a good area to make the error a little less spooky though. Again thanks for the great project :+1:
